### PR TITLE
Spelling and Space Edits

### PR DESCRIPTION
**Pull request by Karla-Isabel-Sandoval**
Cut out an extra O, and got rid of extra space in the What we Worked on Section

### CODE REVIEW

**Comment by segiddins** [comment]
This has merge conflicts.

**Comment by orta** [comment]
@Karla-Isabel-Sandoval this has merge conflicts, do you still want these change snow that we've merged #126  and #125

**Comment by orta** [comment]
Still has conflicts @Karla-Isabel-Sandoval

**Comment by Karla-Isabel-Sandoval** [comment]
@orta, Since we've merged  #126 and #125 we can close 124.

**Pull request closed without merging**
